default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 5  %>

development:
  <<: *default
  database: prog-image-api_development

test:
  <<: *default
  database: prog-image-api_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
