default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 5 %>
  database: <%= ENV["RDS_NAME"] || prog-image-api_development %>
  username: <%= ENV["RDS_USERNAME"] || ENV["USER"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  url: <%= ENV['RDS_URL'] %>

development:
  <<: *default
  database: <%= ENV["RDS_NAME"] || prog-image-api_development %>

test:
  <<: *default
  database: prog-image-api_test

production:
  <<: *default
  database: prog-image-api_production
  url: <%= ENV['RDS_URL'] %>
